### ISSUE TITLE
New markets

### ISSUE THREAD

**Issue by jonathanlking** [dmjio/bittrex#2]
New markets have been added to Bittrex, which causes a runtime error to be thrown when parsing the market names. As markets are likely to be added/removed frequently, is the best way to represent them as data type values (requiring package updates)?

**Comment by dmjio** [comment]
@jonathanlking, if its only confined to this endpoint it should be fine. But if this causes parse failures on private endpoints as well, we might need to rethink. What do you think might be a good alternative?

**Comment by dmjio** [comment]
@jonathanlking one thing we could do is make a catch-all constructor for new markets.

```haskell
data MarketName 
  = NewMarket Text
  | MarketName Market
  deriving (Show, Eq)

instance FromJSON MarketName where
  parseJSON = withText "Market Name" $ \t -> 
    pure $ case readMaybe (T.unpack t) of
       Nothing -> NewMarket t
       Just k -> MarketName k
```

**Comment by jonathanlking** [comment]
@dmjio I think that's good idea 😄

**Comment by dmjio** [comment]
@jonathanlking as you wish :) 2460fd79b67498e728f65d3b043d1d55a8e6ed64
