### ISSUE TITLE
Ord instance for Volume

### ISSUE THREAD

**Issue by qmmdb** [dmjio/bittrex#8]
Hi, why is an `Ord` instance not being derived for all of the types which deal with numbers? Is is it expected that users of this library use `StandAloneDeriving`, or is there a better way for sorting numbers which are retrieved?

**Comment by dmjio** [comment]
https://github.com/dmjio/bittrex/commit/53d04d7455f69b15612552e096ed0721847c7e8e#diff-432bc430b42dcf3ebb6a993f82fed6e7

**Comment by dmjio** [comment]
https://github.com/dmjio/bittrex/commit/53d04d7455f69b15612552e096ed0721847c7e8e#diff-432bc430b42dcf3ebb6a993f82fed6e7
